version: '3'
#https://www.digitalocean.com/community/tutorials/how-to-set-up-laravel-nginx-and-mysql-with-docker-compose-ru
services:
  #Nginx Service
  webserver:
    ports:
      - 31180:80
    volumes:
      - "./dockerfile/webserver/conf.d/:/etc/nginx/conf.d/"